export const ACTION = {
RECRUITER: {
    READY_TO_CONNECT: 'READY_TO_CONNECT',
    PREFILL_MESSAGE: 'PREFILL_MESSAGE',
    RECRUITER_DM_READY: 'RECRUITER_DM_READY',
    RECRUITER_NOT_DMABLE:'RECRUITER_NOT_DMABLE',
    START_PASTING: 'START_PASTING',
    CLOSE_THIS_TAB: 'CLOSE_THIS_TAB',
    RECRUITER_LINKS_FOUND: 'RECRUITER_LINKS_FOUND'
},
CONNECTION: {
    START_TRACKING: "START_TRACKING",
    APPLY_BUTTON_CLICKED: "APPLY_BUTTON_CLICKED",
    START_OBSERVING: "OBSERVING"
},
RENDER: {
    EMAIL_GENERATED:"EMAIL_GENERATED",
    EMAIL_FETCHED: "EMAIL_FETCHED"

}

}as const;

export const JOBSITES = {
LINKEDLN: 
    "linkedin.com/jobs",
SIMPLIFY:
    "simplify.jobs",
WORKDAY:  "myworkdayjobs.com",
GREENHOUSE: "greenhouse.io"
} as const;


export type JOBSITES_TYPE = typeof JOBSITES [keyof typeof JOBSITES];

